version: '3.8'

services:
  pixark:
    image: ghcr.io/ToxicGrease/pixark-server:latest
    ports:
      - "27015:27015/udp"
      - "27016:27016/udp"
      - "7777:7777/udp"
      - "7778:7778/udp"
    environment:
      SESSION_NAME: "GreaseArk"
      MAX_PLAYERS: "20"
      SERVER_PASSWORD: ""
      ADMIN_PASSWORD: "supersecret"
    volumes:
    #Make sure to update this location data IE - /server/location/for/pixark_data/:pixark_data
      - ./pixark_server/pixark_data/:pixark_data
    restart: unless-stopped
    tty: true
    stdin_open: true